import fs from 'fs';
import path from 'path';

interface Candidate {
  candidate_id: string;
  rank: string;
  score: string;
  reasoning: string;
}

export default async function SandboxSection() {
  let candidates: Candidate[] = [];
  
  try {
    // Read the submission.csv generated by our rank.py pipeline
    // process.cwd() in Next.js is the lumina-ai directory
    const csvPath = path.join(process.cwd(), '../submission.csv');
    const fileContents = fs.readFileSync(csvPath, 'utf8');
    
    // Simple CSV parser for the 4-column format
    // Format: candidate_id,rank,score,"reasoning..."
    const lines = fileContents.split('\n').filter(line => line.trim().length > 0);
    
    // Skip header
    for (let i = 1; i < lines.length; i++) {
      const line = lines[i];
      // Regex to split by comma, respecting quotes
      const matches = line.match(/(?:^|,)("(?:[^"]|"")*"|[^,]*)/g);
      
      if (matches && matches.length >= 4) {
        candidates.push({
          candidate_id: matches[0].replace(/^,/, '').replace(/^"|"$/g, '').trim(),
          rank: matches[1].replace(/^,/, '').replace(/^"|"$/g, '').trim(),
          score: matches[2].replace(/^,/, '').replace(/^"|"$/g, '').trim(),
          reasoning: matches[3].replace(/^,/, '').replace(/^"|"$/g, '').replace(/""/g, '"').trim(),
        });
      }
    }
  } catch (error) {
    console.error("Failed to load submission.csv:", error);
  }

  // Display top 20 candidates in the sandbox UI
  const displayCandidates = candidates.slice(0, 20);

  return (
    <section id="sandbox" className="py-24 bg-zinc-900 relative">
      <div className="max-w-7xl mx-auto px-6 lg:px-8">
        <div className="mx-auto max-w-2xl text-center mb-16">
          <h2 className="text-3xl font-bold tracking-tight text-zinc-100 sm:text-4xl">
            Live Ranking Results
          </h2>
          <p className="mt-4 text-lg text-zinc-400">
            Top 20 candidates evaluated against the Redrob JD using our 5-component scoring pipeline. 
            Generated directly from our `submission.csv`.
          </p>
        </div>

        {displayCandidates.length > 0 ? (
          <div className="flex flex-col gap-4">
            {displayCandidates.map((cand) => {
              const scoreFloat = parseFloat(cand.score);
              let scoreColor = "text-emerald-400";
              if (scoreFloat < 0.95) scoreColor = "text-amber-400";
              if (scoreFloat < 0.90) scoreColor = "text-red-400";

              return (
                <div 
                  key={cand.candidate_id}
                  className="bg-zinc-950 border border-zinc-800 rounded-xl p-6 hover:border-zinc-700 transition-colors flex flex-col md:flex-row gap-6 items-start"
                >
                  <div className="flex flex-col items-center justify-center min-w-[80px]">
                    <span className="text-xs font-mono text-zinc-500 uppercase tracking-wider mb-1">Rank</span>
                    <span className="text-3xl font-bold text-zinc-200">#{cand.rank}</span>
                  </div>
                  
                  <div className="flex-1 min-w-0">
                    <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-2 mb-3">
                      <h3 className="text-lg font-mono font-medium text-emerald-300">
                        {cand.candidate_id}
                      </h3>
                      <div className="flex items-center gap-2 bg-zinc-900 px-3 py-1 rounded-full border border-zinc-800">
                        <span className="text-xs text-zinc-400 uppercase tracking-wider">Score</span>
                        <span className={`font-mono font-bold ${scoreColor}`}>
                          {cand.score}
                        </span>
                      </div>
                    </div>
                    
                    <p className="text-sm leading-relaxed text-zinc-300">
                      {cand.reasoning}
                    </p>
                  </div>
                </div>
              );
            })}
          </div>
        ) : (
          <div className="text-center p-12 border border-dashed border-zinc-800 rounded-xl">
            <p className="text-zinc-500">No submission data found. Run rank.py first.</p>
          </div>
        )}
      </div>
    </section>
  );
}
